# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laundry.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlaundry.proto\x12\x07laundry\"y\n\x07Laundry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x13\n\x0bpickup_date\x18\x04 \x01(\t\x12\x15\n\rdelivery_date\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"2\n\rCreateRequest\x12!\n\x07laundry\x18\x01 \x01(\x0b\x32\x10.laundry.Laundry\"!\n\x0e\x43reateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"1\n\x0cReadResponse\x12!\n\x07laundry\x18\x01 \x01(\x0b\x32\x10.laundry.Laundry\"\x10\n\x0eReadAllRequest\"4\n\x0fReadAllResponse\x12!\n\x07laundry\x18\x01 \x03(\x0b\x32\x10.laundry.Laundry\"2\n\rUpdateRequest\x12!\n\x07laundry\x18\x01 \x01(\x0b\x32\x10.laundry.Laundry\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd7\x02\n\x0eLaundryService\x12@\n\rCreateLaundry\x12\x16.laundry.CreateRequest\x1a\x17.laundry.CreateResponse\x12:\n\x0bReadLaundry\x12\x14.laundry.ReadRequest\x1a\x15.laundry.ReadResponse\x12@\n\rUpdateLaundry\x12\x16.laundry.UpdateRequest\x1a\x17.laundry.UpdateResponse\x12@\n\rDeleteLaundry\x12\x16.laundry.DeleteRequest\x1a\x17.laundry.DeleteResponse\x12\x43\n\x0eReadAllLaundry\x12\x17.laundry.ReadAllRequest\x1a\x18.laundry.ReadAllResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laundry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAUNDRY']._serialized_start=26
  _globals['_LAUNDRY']._serialized_end=147
  _globals['_CREATEREQUEST']._serialized_start=149
  _globals['_CREATEREQUEST']._serialized_end=199
  _globals['_CREATERESPONSE']._serialized_start=201
  _globals['_CREATERESPONSE']._serialized_end=234
  _globals['_READREQUEST']._serialized_start=236
  _globals['_READREQUEST']._serialized_end=261
  _globals['_READRESPONSE']._serialized_start=263
  _globals['_READRESPONSE']._serialized_end=312
  _globals['_READALLREQUEST']._serialized_start=314
  _globals['_READALLREQUEST']._serialized_end=330
  _globals['_READALLRESPONSE']._serialized_start=332
  _globals['_READALLRESPONSE']._serialized_end=384
  _globals['_UPDATEREQUEST']._serialized_start=386
  _globals['_UPDATEREQUEST']._serialized_end=436
  _globals['_UPDATERESPONSE']._serialized_start=438
  _globals['_UPDATERESPONSE']._serialized_end=471
  _globals['_DELETEREQUEST']._serialized_start=473
  _globals['_DELETEREQUEST']._serialized_end=500
  _globals['_DELETERESPONSE']._serialized_start=502
  _globals['_DELETERESPONSE']._serialized_end=535
  _globals['_LAUNDRYSERVICE']._serialized_start=538
  _globals['_LAUNDRYSERVICE']._serialized_end=881
# @@protoc_insertion_point(module_scope)
